name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Comando ls
        run: ls -l      
      - name: Docker build service
        run: echo "Docker build service"
      - name: Docker build web app
        run: echo "Docker build web app"
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticar o AWS CLI
        run: echo "Configurar o AWS Configure"
      - name: Configurar o kubectl
        run: echo "Configurar o kubectl"
      - name: Deploy das aplicaçoes
        run: echo "Executar o comando kubectl apply"
